### ISSUE TITLE
Firefox + Weston OSK

### ISSUE THREAD

**Issue by chris-eemn** [OldManYellsAtCloud/meta-browser#136]
I am curious if anyone has any experience using Firefox and the Weston keyboard. When I run firefox the weston keyboard does not ever pop-up.

I can get the keyboard to show up with chromium if I pass in the `--enable-wayland-ime` flag when I launch chromium.

I did some digging and my trail ended with looking at WAYLAND debug logs that show weston advertising `zwp_input_method_v1` and `zwp_text_input_manager_v1` but firefox not binding.

```
[2307619.264] wl_registry@18.global(20, "zwp_input_method_v1", 1)
[2307619.295] wl_registry@18.global(21, "zwp_text_input_manager_v1", 1)
```

Any thoughts on how to use firefox with the Weston keyboard would be greatly appreciated.

My hardware is a TI-skam62evm with a touch screen.

**Comment by OldManYellsAtCloud** [comment]
Personally I'm using (slightly modified version of) wvkbd as n OSK on the PinephonePro. But I remember that I had to enable or install something in GTK itself (or something related) to make it pop up automatically...

/me thinking hard to remember what was that...

**Comment by chris-eemn** [comment]
Thanks for the idea, I will investigate this.

**Comment by OldManYellsAtCloud** [comment]
`gtk3-immodule-wayland` - try adding this as a runtime dependency. I have this in my own firefox.bbappend:

```
RDEPENDS:${PN} += "${@ 'gtk3-immodule-wayland' if 'wayland' in d.getVar('PACKAGECONFIG') and 'touchscreen' in d.getVar('MACHINE_FEATURES') else ''}"
```

**Comment by OldManYellsAtCloud** [comment]
Did `gtk3-immodule-wayland` solve the problem with Weston OSK? Or does this need more investigation?
