### ISSUE TITLE
Review old patches

### ISSUE THREAD

**Issue by OldManYellsAtCloud** [OldManYellsAtCloud/meta-browser#3]
The fork contains a number of patches for ESR 68, however it is quite old. Review if the patches are still relevant, and add them to the layer.

**Comment by skandigraun** [comment]
All patches from the porting folder adapted to the new source, and added back to the layer.

**Comment by skandigraun** [comment]
wayland folder:

- bug1451816-workaround-for-grabbing-popup.patch - potentially relevant for old GTK users, however the patch doesn't apply anymore. Are there users using latest FF with ancient GTK? **Need to revisit.**
- 0001-Bug-1745560-Add-missing-stub-for-wl_proxy_marshal_fl.patch - change is part of Firefox source, patch dropped
- bug1571603-Disable-eglQueryString-nullptr-EGL_EXTENSIONS.patch - patch adapted and included
- 0001-Mark-GLFeature-framebuffer_multisample-as-unsupporte.patch - patch adapted and included
- 0001-GLLibraryLoader-Use-given-symbol-lookup-function-fir.patch - patch added back to layer
