### ISSUE TITLE
langpacks do not work

### ISSUE THREAD

**Issue by bkauler** [OldManYellsAtCloud/meta-browser#50]
Related to this report:

https://github.com/OldManYellsAtCloud/meta-browser/issues/49

I also compiled all the langpacks for firefox 119.0. "about:addons -> Languages" shows them available; however, they are all disabled and cannot be enabled.

**Comment by OldManYellsAtCloud** [comment]
Thanks for the report. I must admit, I tried langpacks only once when I initially updated this layer. Going to look what's going on with this, and fix it during the weekend (at least that's the plan)

**Comment by OldManYellsAtCloud** [comment]
@bkauler I am currently building an image with a fix, not merged yet. If you would like to try it, the changes are fairly simple, you can perform it easily on the running image:

1. Delete the last line in `/usr/lib/firefox/defaults/pref/vendor.js` (could be lib64 on some systems)
2. Delete firefox profile folders (`~/.mozilla` and `~/.cache/mozilla` folders), or just start a new profile
3. Restart Firefox

This should do the trick. Will ping back once it is merged to master.

**Comment by OldManYellsAtCloud** [comment]
Merged - please let me know if you still see incorrect behavior about this.

**Comment by bkauler** [comment]
Yes, langpacks now work!
