### ISSUE TITLE
rust-cssparser wrong branch

### ISSUE THREAD

**Issue by bkauler** [OldManYellsAtCloud/meta-browser#86]
Hi, I got firefox master branch yesterday. One of the patches is wrong, in firefox_125.0.2.bb:

 ` git://github.com/servo/rust-cssparser;protocol=https;branch=master;name=cssparser;destsuffix=cssparser \`

...that must be "branch=main"

**Comment by OldManYellsAtCloud** [comment]
Thank you very much for reporting this. It should be fixed corrected in the head of master branch.
