### ISSUE TITLE
cargo do_compile fail

### ISSUE THREAD

**Issue by bkauler** [OldManYellsAtCloud/meta-browser#87]
I'm compiling in kirkstone, and have meta-rust, which is 1.75.0
I got firefox branch master yesterday, and compile has failed. I see that you have meta-firefox/recipes-devtools/rust, which looks like it is duplicating what I already have in meta-rust.

This is what is failing:

`ERROR: Logfile of failure stored in: /mnt/build/builds/oe/kirkstone/oe-quirky/build-amd64/tmp/work/x86_64-linux/cargo-native/1.75.0-r7/temp/log.do_compile.24047`
...
`| error: failed to run rustc to learn about target-specific information`

I have already edited meta-firefox/recipes-devetools/clang/llvm-project-source.bbappend, removed "kirkstone":

`SRC_URI += '${@bb.utils.contains_any("LAYERSERIES_CORENAMES", "dunfell", `

As I have meta-clang, with clang 14.0.6 and the patches do not work.

I'm wondering, should I just remove all of meta-firefox/recipes-devtools/rust?

**Comment by OldManYellsAtCloud** [comment]
Rust: yes, the rust folder is only needed for the Nanbield release. For other releases you can either delete it, or for example add `BBMASK += "meta-browser/meta-firefox/recipes-devtools/rust/"` to local.conf or similar place, to ignore that folder while parsing. (Once Nanbield is EOL, this folder will go away also with the next FF release. Nanbield will be EOL next week.)

llvm: yes, the patch is only needed for kirkstone. I am going to cherry pick that commit into master in a few moments.

In the past week I did some CI work where these issues are fixed, but unfortunately I missed adding all necessary details to the master branch (including the note about rust), sorry for that. I hope to catch up with all these this weekend.

**Comment by bkauler** [comment]
Hi, just to confirm, I deleted meta-firefox/recipes-devtools/rust and Firefox 125.0.2 compiled ok.

I've got kirkstone with meta-rust 1.75.0 (from master branch April 26) and meta-clang 14.0.6 (from branch kirkstone April 26).

**Comment by OldManYellsAtCloud** [comment]
Thank you for the confirmation.

I believe for now there isn't much to do about this issue, closing it.

If you disagree, feel free to reopen it.
